# Generated by Django 4.1.3 on 2024-11-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthportalapi', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
