# Generated by Django 4.1.3 on 2024-12-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthportalapi', '0004_patientintakeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientintakeform',
            name='emergencycontactphone',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='healthportalapi.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='healthportalapi.user')),
            ],
        ),
    ]
